# GOPATH development mode no longer supported by default post golang 1.16
#export GOPATH=${PWD}/../../../acme/golib:${PWD}/../../../acme/ExternalGoPackages:${PWD}/../

all:
	CGO_ENABLED=1 go build 

clean:
	go clean
